appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: FI9u8QLgCPXqst+unD9dOGF1GPG4a5bDqlK07cCiHj5w0D9xLR8gDE1QJjYo6mn2CqLwAb7QLwFucHkU3KQNDDZQ73TQvtsGkJ0M7OVkB8q/48w/pAjHQP3iwFS2v/raUMdxeU4poVPFXap7rsKpVtKA98haen20e+Z83Joi0DETH8zBIzSUzYHNZGcPhEGCmffE6zT/0mHyUC7r6nr8v/W6z0T2L2l1blqpZD5gd80MTc+EWUkB3C7l5wnVwClHCzejNNnPsqZYaB/LxdyvxI3M3h1hdSvkKWnfxhnurqT8a62UM0QLyRnJowLNDRhdE4YigMXSHqzbIhAlFm5P3w8GK/cn7MjN4oB7PbQ5swcUx7GNq7PvnMnyTrNhoqXYJLKVAvMS+TD9ZegzIYqJ6XkJZjM7OBU5yheFoR97Gky06KBX3HJgVkH/ImGLCljHor9/19yvv/rJLW0ebyuLQu0J320zFAijzTgUDvC46mpkhuNxN3U/gjjn4yS5Cp+EBFAPWUrxV4j/qbDOzBEYj4pnOW3hf+G1m38silxe359TZdvcRMLEsblKRIbavSc5qcfGMKGtLGYt4wQYnuDZ6FKm5TBu5KbDnSTFpYxhyAXcRhUu0jcVyDJN6FEIE/ooixN5WHVdTgUYTBlQuWCfYvB9p+hk4DVzspvicaqmxag=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
